### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by xiexu0210** [WangJian981002/GF-CSL#1]
你好，核心代码还放出来吗

**Comment by WangJian981002** [comment]
> 你好，核心代码还放出来吗

你好，这个repo中除了用到mmcv中的DCNv2以外，其余部分是self-contained的。现在在DOTA数据集上完整训练、测试的代码均已放出。后续会把在HRSC2016和UCAS-AOD数据集上的训练和测试部分整理好上传。
